# Generated by Django 4.2.7 on 2023-11-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktur2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_faktur', models.CharField(max_length=200)),
                ('tgl_faktur', models.DateField()),
                ('id_ms_th_pjk', models.CharField(max_length=200)),
                ('npwp_penjual', models.CharField(max_length=200)),
                ('nama_penjual', models.CharField(max_length=200)),
                ('nama_pembeli', models.CharField(max_length=200)),
                ('nama_barang', models.TextField()),
                ('jml_dpp', models.IntegerField()),
                ('jml_ppn', models.IntegerField()),
            ],
        ),
    ]
