# Generated by Django 4.2.7 on 2023-12-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktur2022',
            name='ALAMAT_PEMBELI',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faktur2022',
            name='NAMA_BARANG',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faktur2022',
            name='NAMA_PEMBELI',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
