# Generated by Django 4.2.7 on 2023-11-08 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faktur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faktur2022',
            options={},
        ),
    ]
